FROM python:3.7.5 as builder

RUN mkdir -p /var/app/current
WORKDIR /var/app/current

COPY . /var/app/current 

ENV VIRTUAL_ENV=/var/app/venv
RUN python -m venv /var/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install -r /var/app/current/requirements-dev.txt
RUN pip install -e /var/app/current/app
        
ENV FLASK_APP=pets_api.run
ENV FLASK_DEBUG=1
ENV FLASK_ENV=development

EXPOSE 5000
CMD [ "/var/app/current/develop.sh" ]